travis:
  "name/repo":
    token: "abc123"
    channel: "#test"

gitlab:
  "name / repo":
    channel: "#test"

# See Cinch::Configuration::Bot for settings
irc:
  :server: irc.example.com
  :port: 6667
  :nick: git-bot
  :ssl:
    :use: true

sinatra:
  port: 4567
